### ISSUE TITLE
Update to more recent JDK state

### ISSUE THREAD

**Issue by ebresie** [AdoptOpenJDK/lambda-tutorial#17]
This is a great learning project.

However I’ve noticed a lot of the content is focused on either EA or earlier versions of IDEs (in a Wiki) or compatible JDK.  

Given latest versions of JDK (as if request 14-15) and with new release schedule, suggest 

(1) updating JDK references in readme and source where applicable
(2) for IDE setup wiki pages changes since JDK 8 is readily supported if not mandatory now with recent IDE versions.

**Comment by Grundlefleck** [comment]
@ebresie good shout. The instructions look a little bit like cave drawings from a different era. I'll give some of the details a spruce.

**Comment by Grundlefleck** [comment]
The entirety of the wiki looked defunct (how to configure a lambda compatible IDE) so I've removed all the pages.

@karianna I had a local commit ready to push to remove outdated cruft from README and setup, but don't have push access to master. Is that an oversight or could it just possibly be that policy has changed since 2013 :)

**Comment by karianna** [comment]
> The entirety of the wiki looked defunct (how to configure a lambda compatible IDE) so I've removed all the pages.
> 
> @karianna I had a local commit ready to push to remove outdated cruft from README and setup, but don't have push access to master. Is that an oversight or could it just possibly be that policy has changed since 2013 :)

You're an admin now :-)

**Comment by Grundlefleck** [comment]
Updated the repo. 

Have also filled out the solutions to the default method on interfaces exercise -- I didn't expect this tutorial was still getting used 6+ years later, and don't like the idea it's incomplete :)

Thanks for reporting @ebresie
